// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://xyspuhuhblivpgwajsyp.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Inh5c3B1aHVoYmxpdnBnd2Fqc3lwIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDgxNDI3NTMsImV4cCI6MjA2MzcxODc1M30.LZqhA9TsiaG9_dn4KWR-zCwR31QXxgA5QqZD3Jp-Nos";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);